version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: taskmgr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-taskmanager}
      MYSQL_USER: ${MYSQL_USER:-wesley}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: taskmgr-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-taskmanager}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-wesley}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-123456}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_JWT_SECRET: ${JWT_SECRET:-changemechangemechangemechangeme}
      SPRING_SECURITY_JWT_EXPIRATION: 86400000
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: taskmgr-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
