spring:
  application:
    name: task-manager-api
  
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

